namespace RentaVehiculo.UI.Vehiculos
{
    partial class VehiculoForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            txtMarca = new TextBox();
            txtModelo = new TextBox();
            numAño = new NumericUpDown();
            txtPlaca = new TextBox();
            numKm = new NumericUpDown();
            numPrecio = new NumericUpDown();
            cboEstado = new ComboBox();
            chkActivo = new CheckBox();
            cboSucursal = new ComboBox();
            btnGuardar = new Button();
            btnCancelar = new Button();
            label1 = new Label();
            label2 = new Label();
            label3 = new Label();
            label4 = new Label();
            label5 = new Label();
            label6 = new Label();
            label7 = new Label();
            label8 = new Label();
            label9 = new Label();
            SuspendLayout();
            txtMarca.Location = new Point(180, 52);
            txtMarca.Name = "txtMarca";
            txtMarca.Size = new Size(300, 23);
            txtMarca.TabIndex = 0;
            txtModelo.Location = new Point(180, 92);
            txtModelo.Name = "txtModelo";
            txtModelo.Size = new Size(300, 23);
            txtModelo.TabIndex = 1;
            numAño.Location = new Point(180, 132);
            numAño.Maximum = new decimal(new int[] { 2100, 0, 0, 0 });
            numAño.Minimum = new decimal(new int[] { 1990, 0, 0, 0 });
            numAño.Name = "numAño";
            numAño.Size = new Size(120, 23);
            numAño.TabIndex = 2;
            numAño.Value = new decimal(new int[] { 2024, 0, 0, 0 });
            txtPlaca.Location = new Point(180, 172);
            txtPlaca.Name = "txtPlaca";
            txtPlaca.Size = new Size(140, 23);
            txtPlaca.TabIndex = 3;
            numKm.Location = new Point(180, 212);
            numKm.Maximum = new decimal(new int[] { 10000000, 0, 0, 0 });
            numKm.Name = "numKm";
            numKm.Size = new Size(120, 23);
            numKm.TabIndex = 4;
            numPrecio.Location = new Point(180, 252);
            numPrecio.DecimalPlaces = 2;
            numPrecio.Maximum = new decimal(new int[] { 1000000, 0, 0, 0 });
            numPrecio.Name = "numPrecio";
            numPrecio.Size = new Size(120, 23);
            numPrecio.TabIndex = 5;
            cboEstado.DropDownStyle = ComboBoxStyle.DropDownList;
            cboEstado.Location = new Point(180, 290);
            cboEstado.Name = "cboEstado";
            cboEstado.Size = new Size(300, 23);
            cboEstado.TabIndex = 6;
            chkActivo.AutoSize = true;
            chkActivo.Location = new Point(180, 332);
            chkActivo.Name = "chkActivo";
            chkActivo.Size = new Size(60, 19);
            chkActivo.TabIndex = 7;
            chkActivo.Text = "Activo";
            cboSucursal.DropDownStyle = ComboBoxStyle.DropDownList;
            cboSucursal.Location = new Point(180, 368);
            cboSucursal.Name = "cboSucursal";
            cboSucursal.Size = new Size(300, 23);
            cboSucursal.TabIndex = 8;
            btnGuardar.Location = new Point(180, 424);
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Size = new Size(115, 38);
            btnGuardar.TabIndex = 9;
            btnGuardar.Text = "Guardar";
            btnGuardar.UseVisualStyleBackColor = true;
            btnGuardar.Click += btnGuardar_Click;
            btnCancelar.DialogResult = DialogResult.Cancel;
            btnCancelar.Location = new Point(305, 424);
            btnCancelar.Name = "btnCancelar";
            btnCancelar.Size = new Size(115, 38);
            btnCancelar.TabIndex = 10;
            btnCancelar.Text = "Cancelar";
            btnCancelar.UseVisualStyleBackColor = true;
            label1.AutoSize = true;
            label1.Location = new Point(20, 55);
            label1.Name = "label1";
            label1.Size = new Size(43, 15);
            label1.Text = "Marca:";
            label2.AutoSize = true;
            label2.Location = new Point(20, 95);
            label2.Name = "label2";
            label2.Size = new Size(51, 15);
            label2.Text = "Modelo:";
            label3.AutoSize = true;
            label3.Location = new Point(20, 135);
            label3.Name = "label3";
            label3.Size = new Size(32, 15);
            label3.Text = "Año:";
            label4.AutoSize = true;
            label4.Location = new Point(20, 175);
            label4.Name = "label4";
            label4.Size = new Size(38, 15);
            label4.Text = "Placa:";
            label5.AutoSize = true;
            label5.Location = new Point(20, 215);
            label5.Name = "label5";
            label5.Size = new Size(83, 15);
            label5.Text = "Kilometraje:";
            label6.AutoSize = true;
            label6.Location = new Point(20, 255);
            label6.Name = "label6";
            label6.Size = new Size(91, 15);
            label6.Text = "Precio por día:";
            label7.AutoSize = true;
            label7.Location = new Point(20, 295);
            label7.Name = "label7";
            label7.Size = new Size(45, 15);
            label7.Text = "Estado:";
            label8.AutoSize = true;
            label8.Location = new Point(20, 375);
            label8.Name = "label8";
            label8.Size = new Size(108, 15);
            label8.Text = "Sucursal (opc.):";
            label9.AutoSize = true;
            label9.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            label9.Location = new Point(20, 14);
            label9.Name = "label9";
            label9.Size = new Size(62, 20);
            label9.Text = "Vehículo";
            AcceptButton = btnGuardar;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            AutoScroll = true;
            CancelButton = btnCancelar;
            ClientSize = new Size(520, 500);
            Padding = new Padding(12);
            Controls.Add(label9);
            Controls.Add(label8);
            Controls.Add(label7);
            Controls.Add(label6);
            Controls.Add(label5);
            Controls.Add(label4);
            Controls.Add(label3);
            Controls.Add(label2);
            Controls.Add(label1);
            Controls.Add(btnCancelar);
            Controls.Add(btnGuardar);
            Controls.Add(cboSucursal);
            Controls.Add(chkActivo);
            Controls.Add(cboEstado);
            Controls.Add(numPrecio);
            Controls.Add(numKm);
            Controls.Add(txtPlaca);
            Controls.Add(numAño);
            Controls.Add(txtModelo);
            Controls.Add(txtMarca);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "VehiculoForm";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Vehículo";
            ResumeLayout(false);
            PerformLayout();
        }

        private TextBox txtMarca;
        private TextBox txtModelo;
        private NumericUpDown numAño;
        private TextBox txtPlaca;
        private NumericUpDown numKm;
        private NumericUpDown numPrecio;
        private ComboBox cboEstado;
        private CheckBox chkActivo;
        private ComboBox cboSucursal;
        private Button btnGuardar;
        private Button btnCancelar;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
    }
}
